Modules and Commandlets Update
-Add and Search User function Added.

-Mongoose Commander and Inquirer Dependency Added.

- added 75 packages, and audited 76 packages

-Has errors:
MongooseError: Operation `users.insertOne()` buffering timed out after 10000ms

- Bugs fixed:
MongoParseError: option usemongoclient is not supported
(current URL string parser is deprecated)